### ISSUE TITLE
Not working with project which was integrated with react-native by CocoaPods

### ISSUE THREAD

**Issue by hubertwang** [react-community/react-native-image-picker#455]
Hi,

I am developing a project which was integrated with react-native by CocoaPods manually. In other words, my project is not generated by react-native-cli. Everything works fine until react-native 0.40.0 released. 

As we know, there was a breaking change which affects the naming space of react-native. However, the change seems has side effect over sub-projects. We are not able to access react-native framework anymore. All the sub-projects failed to compile, including ReactNativeImagePicker.

Actually, it works with project generated by react-native-cli, but not with project using CocoaPods. Anyone has an idea to fix it?

**Comment by imjameshall** [comment]
Whats the error you're getting?

**Comment by hubertwang** [comment]
Can not find RCTBridgeModule.h, Xcode compile failed.
I tried both "RCTBridgeModule.h" and <React/RCTBridgeModule.h>, but they all failed to compile.

**Comment by jhellman** [comment]
@hubertwang I'm dealing with the same issue - have you found a solution?

**Comment by jhellman** [comment]
Huh, not sure how I didn't notice the podspec before, but adding this library to my non react-native-cli app using Cocoapods via the included podspec solved my problem.  Might be worth an update to the readme to address using cocoapods for installation on iOS.

**Comment by jpapillon** [comment]
Is there a way to fix this without using the pod for this library? There must be some include settings somewhere that I just can't find.

**Comment by hubertwang** [comment]
@jhellman I haven't found any solution to this issue yet. Thanks for your update, I'll give it a try.

**Comment by marcshilling** [comment]
As far as I know, this is out of my control. Can you take this issue to either the React Native repo or Cocoapods, or provide me with some direction of what I'm not doing correctly here?

**Comment by hubertwang** [comment]
@marcshilling Our team haven't started to fix this issue yet. I'll let you know if we got any clue to fix this issue.

**Comment by oillamp** [comment]
the same issue in rn 0.41

**Comment by pseudorandumb** [comment]
Like @jhellman said, adding via the podfile rather than 'react-native link' worked for me. 
In my podfile:
```
pod 'react-native-image-picker', :path => 'node_modules/react-native-image-picker'
```
I'm using:
react-native: 42.0-rc.2 (also tried 41.0)
react-native-image-picker: 0.25.5

**Comment by BigPun86** [comment]
@pseudorandumb Shoudn´t it be `pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'`?

**Comment by pseudorandumb** [comment]
Yea @BigPun86 that may be more common for most people. My example works for me, needs to be adapted depending on your relative pathing to where the node_modules folder is located.

**Comment by haitaoli** [comment]
Closing this issue since it has been inactive for two months, and it's not an issue in this project.

**Comment by mgfjxxiexiaolong** [comment]
@pseudorandumb I works to me. Thanks.
