### ISSUE TITLE
Can we "tag" images retrieved by the image picker ?

### ISSUE THREAD

**Issue by ajonno** [react-community/react-native-image-picker#542]
Our app needs to allow a user to pick X photos and/or take photos, and then 'assign' them to a Note.

Is it possible to "tag" a selected image on iOS and Droid via this library, so that later we can query via that tag to display the required images for a given Note ?

**Comment by haitaoli** [comment]
This library does not modify image content or meta data. If the image is already in the library you can try matching the url or file name.
