### ISSUE TITLE
Why are image files appearing in finder as greyed out ? then they disappear.

### ISSUE THREAD

**Issue by ajonno** [react-community/react-native-image-picker#543]
something i dont understand is why do image files that are landing ok in the ../../../.../images path on the simulator - show up as greyed out (which i can see from monitoring the folder in Finder - and then they just dissapear, so then i cant do anything with them afterwards ?

```
         storageOptions: {
            skipBackup: true,
            path: 'images'
         }

```

![image](https://cloud.githubusercontent.com/assets/3005269/24693447/fa175804-1a20-11e7-8ca2-c97ca03a9f3e.png)

**Comment by marcshilling** [comment]
iOS or Android?

**Comment by ajonno** [comment]
Sorry should have noted this was on iOS.

**Comment by marcshilling** [comment]
Ok. You mention observing the ../../../../images folder. What exactly is that path? Specifying `storageOptions` should save the photo in an images folder in the application's Documents directory. Is it possible you're observing the temp directory? The response object should return the path the image gets saved in.

**Comment by ajonno** [comment]
that absolutely could be it. 

here is the path via console.log for a test i did just now:
```/Users/angusjohnston/Library/Developer/CoreSimulator/Devices/CBB7FA55-6E22-4345-8DCE-359686A5998B/data/Containers/Data/Application/B8C5E76E-1216-4956-80D9-CE7B668BFBF7/Documents/images/F518ACE7-73A5-4BEA-B8FD-802D8190EEC4.jpg```

**Comment by marcshilling** [comment]
That seems correct. So the file isn't persisting you're saying?

**Comment by ajonno** [comment]
yes correct. this might have nothing to do with it as im just getting familiar with the api, but if i comment out .close() i can see the image remains in the folder, i can open it etc.
ie.
```
//blob.close();
```

![image](https://cloud.githubusercontent.com/assets/3005269/24731246/20732326-1aac-11e7-95b9-0167f8025a6d.png)

**Comment by marcshilling** [comment]
`blob.close();`
Where are you putting this code?

**Comment by ajonno** [comment]
Sorry for delay in getting back on this just been flat out. The storage options appear to be behaving correctly and I suspect it was something I was doing incorrectly. Really appreciate your help/follow up on this.
