### ISSUE TITLE
Can anyone help me. I got response.path and response.uri. But how can we save a file on the web server?

### ISSUE THREAD

**Issue by ShanthiSenguttuvan** [react-community/react-native-image-picker#564]
* Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.

--- Delete everything above this line ---

### Description

Explain what you did, what you expected to happen, and what actually happens.

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by ShanthiSenguttuvan** [comment]
I have stored the response.data in my database and tried to download as a image file using react-native-fetch-blob but i got error bad base 64? Can anyone help me?

**Comment by haitaoli** [comment]
This issue isn't related to image picker module.

**Comment by ShanthiSenguttuvan** [comment]
yeah this is not an image picker issue. React-native-image-picker is a best module and its working good.  But i don't know how to create  a image file on my server with the response given by react-native-image-picker.

**Comment by korgara** [comment]
@ShanthiSenguttuvan 
You should use lib like this https://github.com/PhilippKrone/react-native-fileupload
