### ISSUE TITLE
How to upload selected image with Relay mutation

### ISSUE THREAD

**Issue by matart15** [react-community/react-native-image-picker#566]
I am using relay.
https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#getfiles

relay uses getFiles on mutation to send files to server. But it seems getFiles function  must return `File` object.

```
class AttachDocumentMutation extends Relay.Mutation {
  getFiles() {
    return {
      file: this.props.file,
    };
  }
}
class FileUploader extends React.Component {
  handleSubmit() {

ImagePicker.showImagePicker(options, (response) => {
    var fileToAttach = response;
    Relay.Store.commitUpdate(
      new AttachDocumentMutation({file: fileToAttach})
    );
}
  }
}
```

Relay responds with `"Syntax Error GraphQL request (1:1) Unexpected EOF↵↵1: ↵   ^↵"`

How can I upload response with `getFiles`?

**Comment by matart15** [comment]
Ok It seems error occurs only when `remote debugging` is on.
If disable it it works.

Any Idea how to debug request.

**Comment by matart15** [comment]
Ok I figured it out. 
It is related to this (https://github.com/react-community/react-native-image-picker/issues/557)

because of file type is not in object backend does not recognize input file.

**Comment by vzhen** [comment]
@matart15 what does it mean?
my response file type always return null. Do you know why?

**Comment by matart15** [comment]
Mine was null too. I don't know the reason. But I assigned it manually. Because i knew my file would be 'image/png'. Then my php backend received uploaded files
