### ISSUE TITLE
With Android device, once select "take photos" or "choose from library", App will crash ~!

### ISSUE THREAD

**Issue by Calvin92** [react-community/react-native-image-picker#582]
But on Genymotion simulator, everything is OK.

I captured the certain error,  it seems there is conflict with `react-native-navigation`, but I don't know which file I can modify to fix this issue.

error log: 

```
FATAL EXCEPTION: mqt_native_modules
Process: com.aotumeeting, PID: 16467
java.lang.UnsupportedOperationException: NavigationActivity must implement OnImagePickerPermissionsCallback
at com.imagepicker.ImagePickerModule.permissionsCheck(ImagePickerModule.java:594)
at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:225)
at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:203)
at com.imagepicker.ImagePickerModule$2.onTakePhoto(ImagePickerModule.java:159)
at com.imagepicker.utils.UI$1.onClick(UI.java:54)
```

**Comment by aarontrank** [comment]
You either need to have NavigationActivity implement OnImagePickerPermissionsCallback or you need to modify ImagePickerModule to cast the activity to a PermissionAwareActivity instead of an OnImagePickerPermissionsCallback.

See PermissionAwareActivity line 576-597, Here's the change I made:

```
else
      {
        String[] PERMISSIONS = {Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CAMERA};
        if (activity instanceof ReactActivity)
        {
          ((ReactActivity) activity).requestPermissions(PERMISSIONS, requestCode, listener);
        }
        else if (activity instanceof PermissionAwareActivity)
        {
          ((PermissionAwareActivity) activity).requestPermissions(PERMISSIONS, requestCode, listener);
        }
        else
        {
          final String errorDescription = new StringBuilder(activity.getClass().getSimpleName())
                  .append(" must implement ")
                  .append(PermissionAwareActivity.class.getSimpleName())
                  .toString();
          throw new UnsupportedOperationException(errorDescription);
        }
        return false;
 }
```

**Comment by Calvin92** [comment]
@aarontrank Awesome~~   It helps me  ~   Many thanks~

**Comment by mrxrinc** [comment]
Hi @aarontrank 
I got a real problem using image picker with react-native-navigation :(
already done ur solution and one in here:
https://github.com/react-community/react-native-image-picker/pull/580/files

but still getting this red screen error and nothing works :(

Could not invoke ImagePickerManager.launchImageLibrary
null
No virtual method requestPermissions([Ljava/lang/String;l)V in class Lcom/reactnativeenavigation/controllers/NavigationActivity; or its super classes (declaration of 'com.reactnativenavigation.controllers.NavigationActivity' appears in /data/app/com.projectName-1/base.apk)

please help me

**Comment by aarontrank** [comment]
Hey @mrxrinc , sorry for delay, just seeing this.  Can you post in your code if this is still a problem?  The error you noted above implies you are not calling "requestPermissions" on an activity.

**Comment by ianzitow** [comment]
@aarontrank your code worked like a charm, thank you so much! why not you make a PR?

**Comment by aarontrank** [comment]
@ianzitow I think some people (including the project owner) want implement OnImagePickerPermissionsCallback instead using PermissionAwareActivity.  Also, the project owner has a sizable backlog of pull requests... Including another one of mine!

**Comment by mfekim** [comment]
Hi @aarontrank,

Thank you for your solution! I think we can just replace ReactActivity by PermissionAwareActivity since ReactActivity implements PermissionAwareActivity.

Current code
```
...
String[] PERMISSIONS = {Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CAMERA};
if (activity instanceof ReactActivity)
{
  ((ReactActivity) activity).requestPermissions(PERMISSIONS, requestCode, listener);
}
else if (activity instanceof OnImagePickerPermissionsCallback)
{
  ((OnImagePickerPermissionsCallback) activity).setPermissionListener(listener);
  ActivityCompat.requestPermissions(activity, PERMISSIONS, requestCode);
}
else
{
  final String errorDescription = new StringBuilder(activity.getClass().getSimpleName())
          .append(" must implement ")
          .append(OnImagePickerPermissionsCallback.class.getSimpleName())
          .toString();
  throw new UnsupportedOperationException(errorDescription);
}
return false;
...
```

New solution
```
...
String[] PERMISSIONS = {Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CAMERA};
if (activity instanceof PermissionAwareActivity)
{
  ((PermissionAwareActivity) activity).requestPermissions(PERMISSIONS, requestCode, listener);
}
else if (activity instanceof OnImagePickerPermissionsCallback)
{
  ((OnImagePickerPermissionsCallback) activity).setPermissionListener(listener);
  ActivityCompat.requestPermissions(activity, PERMISSIONS, requestCode);
}
else
{
  final String errorDescription = new StringBuilder(activity.getClass().getSimpleName())
          .append(" must implement ")
          .append(OnImagePickerPermissionsCallback.class.getSimpleName())
          .toString();
  throw new UnsupportedOperationException(errorDescription);
}
return false;
...
```

**Comment by shahidsm93** [comment]
A very simple thing, until I found out that ImagePicker library wants all three permissions : 

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA"/>

Even if I was not targeting camera, it checks for all three and then requests permission.

**Comment by shahidsm93** [comment]
This library checks for all three permissions, even if you are not targeting camera, so specify them all in your android manifest file :


`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
 <uses-permission android:name="android.permission.CAMERA"/>`
