### ISSUE TITLE
Uploading an image in react-native using react-native-image-picker

### ISSUE THREAD

**Issue by openqubit** [react-community/react-native-image-picker#604]
I have just initialized a basic react-native project and its running in the emulator. I have as well installed this package https://github.com/react-community/react-native-image-picker

and i am trying to upload an image. The code is simple as i have just added some code to handle image upload

    /**
     * Sample React Native App
     * https://github.com/facebook/react-native
     * @flow
     */
    
    import React, { Component } from 'react';
    import {
      AppRegistry,
      StyleSheet,
      Button,
      Text,
      Image,
      Alert,
      View
    } from 'react-native';
    
    
    var ImagePicker = require('react-native-image-picker');
    
    var options = {
      title: 'Select Avatar',
      customButtons: [
        {name: 'fb', title: 'Choose Photo from Facebook'},
      ],
      storageOptions: {
        skipBackup: true,
        path: 'images'
      }
    };
    
    
    const onPressLearnMore = () => { 
    
    ImagePicker.launchImageLibrary(options, (response)  => {
    
    let source = { uri: response.uri };
    
        this.setState({
          avatarSource: source
        });
      
    });
    
    //Alert.alert('Button has been pressed!');
    };
    
    export default class AwesomeProject extends Component {
    	constructor() {
          super()
          this.state = {
             avatarSource: 'image.jpg'
          }
       }
       
      render() {
        return (
    	
          <View style={styles.container}>
            <Text style={styles.welcome}>
              Welcome to React Native!
            </Text>
            <Text style={styles.instructions}>
              To get started, edit index.android.js
            </Text>
            <Button onPress={onPressLearnMore} title="Upload Image" color="#841584" accessibilityLabel="Learn more about this purple button" />
    		
    		<Image source={this.state.avatarSource} style={styles.uploadAvatar} />
          </View>
        );
      }
    }
    
    const styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
      },
      welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
      },
      instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
      },
    });
    
    AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

I get this error when i run this on the emulator

    undefined is not a function (evaluating '_this.setState({
          avatarSource: source
        })')
    <unknown>
        index.android.bundle?platform=android&dev=true&hot=false&minify=false:1274:19
    __invokeCallback
        index.android.bundle?platform=android&dev=true&hot=false&minify=false:4818:21
    <unknown>
        index.android.bundle?platform=android&dev=true&hot=false&minify=false:4664:32
    __guard
        index.android.bundle?platform=android&dev=true&hot=false&minify=false:4753:11
    invokeCallbackAndReturnFlushedQueue
        index.android.bundle?platform=android&dev=true&hot=false&minify=false:4663:19

**Comment by syardumi** [comment]
More than likely, the "this" from your code chunk:

```
const onPressLearnMore = () => { 

ImagePicker.launchImageLibrary(options, (response)  => {

    let source = { uri: response.uri };

    this.setState({
      avatarSource: source
    });
  
});
```
is trying to reference the caller object and not the instance of AwesomeProject to which you want to set the state. The way I would tackle it is to move the onPressLearnMore function to underneath the AwesomeProject class. Then, in the constructor of the class, you'll want to have a line:

`this.onPressLearnMore = this.onPressLearnMore.bind(this);`

in order for the instance of the class to be accessible and usable in the function. If you still end up with the same error, it'll be because "this" is trying to reference the ImagePicker object. To combat that, you can change your function to:

```
const onPressLearnMore = () => { 

var _this = this;

ImagePicker.launchImageLibrary(options, (response)  => {

    let source = { uri: response.uri };

    _this.setState({
      avatarSource: source
    });
  
});
```

**Comment by openqubit** [comment]
```
I have modified the code as you had suggested

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Button,
  Text,
  Image,
  Alert,
  View
} from 'react-native';


var ImagePicker = require('react-native-image-picker');

var options = {
  title: 'Select Avatar',
  customButtons: [
    {name: 'fb', title: 'Choose Photo from Facebook'},
  ],
  storageOptions: {
    skipBackup: true,
    path: 'images'
  }
};


export default class AwesomeProject extends Component {
	constructor() {
		super()
      this.onPressLearnMore = this.onPressLearnMore.bind(this);
   };
   


  render() {
    return (
	
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Button onPress={onPressLearnMore} title="Upload Image" color="#841584" accessibilityLabel="Learn more about this purple button" />
		
		<Image source={this.state.avatarSource} style={styles.uploadAvatar} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

const onPressLearnMore = () => { 

var _this = this;

ImagePicker.launchImageLibrary(options, (response)  => {

    let source = { uri: response.uri };

    _this.setState({
      avatarSource: source
    });
  
});
};

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

but i get this error

undefined is not an object (evaluating '_this2.onPressLearnMore.bind')
AwesomeProject
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:1276:54
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24196:31
measureLifeCyclePerf
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24020:14
_constructComponentWithoutOwner
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24195:36
_constructComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24181:52
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24074:40
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23244:49
mountChildren
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:27361:56
initializeChildren
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:27137:41
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:27197:28
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23244:49
performInitialMount
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24247:48
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24151:40
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23244:49
mountChildren
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:27361:56
initializeChildren
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:27137:41
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:27197:28
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23244:49
performInitialMount
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24247:48
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24151:40
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23244:49
performInitialMount
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24247:48
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24151:40
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23244:49
performInitialMount
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24247:48
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24151:40
mountComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23244:49
mountComponentIntoNode
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23100:46
perform
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23817:24
batchedMountComponentIntoNode
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23107:22
perform
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23817:24
batchedUpdates
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:24966:33
batchedUpdates
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23693:41
renderComponent
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23154:32
render
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:23022:42
renderApplication
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:45842:21
run
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:45625:33
runApplication
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:45669:26
__callFunction
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:4781:47
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:4639:29
__guard
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:4753:11
callFunctionReturnFlushedQueue
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:4638:19


```

**Comment by syardumi** [comment]
Try moving the onPressLearnMore function like so:
```
export default class AwesomeProject extends Component {
	constructor() {
		super()
      this.onPressLearnMore = this.onPressLearnMore.bind(this);
   };

   onPressLearnMore = () => { 

     var _this = this;

     ImagePicker.launchImageLibrary(options, (response)  => {

       let source = { uri: response.uri };

       _this.setState({
         avatarSource: source
       });
  
   });

   render() {
    return (
	
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Button onPress={onPressLearnMore} title="Upload Image" color="#841584" accessibilityLabel="Learn more about this purple button" />
		
		<Image source={this.state.avatarSource} style={styles.uploadAvatar} />
      </View>
    );
  }
}
```

**Comment by openqubit** [comment]
That gives onPressLearnMore  is undefined. Alternatively, you can run this code https://github.com/GeekyAnts/NativeBase/issues/918 in your machine and see what i see. Its a small project with few dependencies so it should build fast.
