### ISSUE TITLE
Execution failed for task ':react-native-maps:processReleaseResources'.

### ISSUE THREAD

**Issue by gjae** [react-community/react-native-image-picker#623]
Hello friends!

I'm using react native 0.45 and airbnb/react-native-maps for use MapView component in a physical devices (i have installed google play services) with android version 4.4, but i have the following problem:

`:react-native-maps:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 23.55 secs
`
help me please

**Comment by dodevski** [comment]
The same issue, any help?

**Comment by RajaSaravanan** [comment]
https://github.com/react-community/react-native-image-picker/issues/882
