### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by kelvinblade** [react-community/react-native-image-picker#677]
On Android, Take Photo and Choose from Gallery works.
On iOS, Choose from Gallery works.
But when I Take Photo and try to upload to my backend, I get this error

`invalid byte sequence in UTF-8`

The image uri is fine because the preview displays properly using <Image />
Only the photo from iOS Take Photo is not working. Any ideas?

**Comment by winescout** [comment]
Mind describing what you discovered on this issue?  I'm looking at the same behavior, and beginning to dive into it.

**Comment by toneplex** [comment]
I've also just run into this issue. Has anyone solved it?

**Comment by toneplex** [comment]
The solution I came up with, is to just send the base64 data to the server instead of posting the file.

**Comment by dinhtu0802** [comment]
Has anyone solved it? same issue.

**Comment by bravemaster619** [comment]
https://stackoverflow.com/q/62635982/11792577
