### ISSUE TITLE
Option to keep original color space of the image in RGB

### ISSUE THREAD

**Issue by ayildirim** [react-community/react-native-image-picker#678]
### Description

Can not use returned image by response.uri in Unity3D, because it is CMYK formatted. Can you retain RGB original format of the image?

I get error below: 

> Wrong JPEG library version: library is 90, caller expects 62

### How to repeat issue and example

- Take a photo on iPhone, move it over to Macbook
- Use it in a Unity3D project and see it works
- Use Photoshop to simulate the conversion image picker is doing to file by, setting Color Space to CMYK in Photoshop.
- You will see image can not be used Unity3D
- Same thing happens when you are using React & Unity3D together with image picker in middle.

### Solution

Add option when saving JPG file for color space with RGB option, or just keep original.

### Additional Information

* React Native version: irrelevant
* Platform: iOS
* Development MacOS
* Dev tools: Unity 5.3.2, Xcode 8

### Useful material on setting color space for UIImage object
https://stackoverflow.com/questions/3284185/get-pixel-color-of-uiimage
https://stackoverflow.com/questions/40331394/how-to-convert-png-image-to-cmyk-in-ios

**Comment by JugalRupela** [comment]
Hi Ayildirim,
I just got stuck at the same spot, I'm creating a app in unity which loads the images uploaded by client in realtime.
As I dont have control over the JPG color space, I also noticed that the CMYK images cant be load.
were you manage to figure out any solution in unity3D?

**Comment by ayildirim** [comment]
@JugalRupela I ended up re-processing images in OpenCV and converting them to Jpeg, then using on Unity3D to solve it.

**Comment by JugalRupela** [comment]
that's sad, similarly I ended up writing a php script to convert CMYK to RGB colour mode before using in unity3d..
anyways thanks for the reply @ayildirim.
