### ISSUE TITLE
iOS - allowEditing: true, trimming video not working

### ISSUE THREAD

**Issue by bz123** [react-community/react-native-image-picker#695]
When choosing a video from the cameraroll, on the very top there is a section where I am supposed to trim a video. I trim it down in length, then select choose at the bottom - right, it says trimming video, and after that the video still appears as full length.

Any ideas?

* React Native version: 0.43.3
* Platform: iOS
* Development Operating System: MacOs
* Dev tools: Xcode

**Comment by BaderSerhan** [comment]
hello, did you find a solution for this?

**Comment by maxschmeling** [comment]
This is still an issue. Confirmed with the latest version of this library on iOS 13. @Johan-dutoit
