### ISSUE TITLE
GIF support on Android

### ISSUE THREAD

**Issue by teyou** [react-community/react-native-image-picker#724]
### Description

I try to select a gif file in Android and it returns as jpg file?
It only happens when I set the `quality configuration to below 1`.
However, it works as intended in IOS.

### How to repeat issue and example

use below configuration will convert into jpg file
my configuration
```
var options = {
      cameraType: 'back', // 'front' or 'back'
      mediaType: 'photo', // 'photo' or 'video'
      quality: 0.6, // 0 to 1, photos only      
      allowsEditing: false,
      noData: false,
      storageOptions: {
        skipBackup: true,
        path: 'images'
      }
    };
```

Your explanation here and source code or link

### Solution

In Android, we need to check if it is a GIF file, it should not compress the image even when the quality configuration is below 1

### Additional Information

* React Native version: 0.49.3]
* Platform: Android
* Development Operating System: MacOS

**Comment by charpeni** [comment]
Fixed in #725.
