### ISSUE TITLE
Video option does NOT return type and base64data

### ISSUE THREAD

**Issue by ProteanDev** [react-community/react-native-image-picker#745]
When will this be available?

**Comment by delia-m** [comment]
type and data - photos only 

you can check doc:
https://github.com/react-community/react-native-image-picker#options

**Comment by ProteanDev** [comment]
Do you guys ever plan to fully support videos?

**Comment by gengjiawen** [comment]
Why would you like to do that ? The whole video date load into memory is not a good idea.

**Comment by ProteanDev** [comment]
Because I need to, unless you can suggest an alternative.

**Comment by gengjiawen** [comment]
This is most likely will result into OOM. If you really want to this, you can use native api.

**Comment by ProteanDev** [comment]
It's alright, I already got around the problem.
I use react-native-fs and react-native-get-real-path for android since this still returns the uri for the video. 

react-native-fs can return that sweet base64 string converted files

**Comment by kodayashi** [comment]
Agreed, unless I'm missing something. I need to upload videos to S3 with presigned URLs. AFAIK, that requires access to the raw data, the AWS PUT API doesn't support multipart/form uploads.
