### ISSUE TITLE
crash in ios11, iphone 8

### ISSUE THREAD

**Issue by chenminhua** [react-community/react-native-image-picker#746]
### Description
I just run the example code at my iphone8 device, but when i click the picker, app crashed with signal SIGABRT error

`libsystem_kernel.dylib`__abort_with_payload:
    0x186b700a0 <+0>:  mov    x16, #0x209
    0x186b700a4 <+4>:  svc    #0x80
->  0x186b700a8 <+8>:  b.lo   0x186b700c0               ; <+32>
    0x186b700ac <+12>: stp    x29, x30, [sp, #-0x10]!
    0x186b700b0 <+16>: mov    x29, sp
    0x186b700b4 <+20>: bl     0x186b52238               ; cerror_nocancel
    0x186b700b8 <+24>: mov    sp, x29
    0x186b700bc <+28>: ldp    x29, x30, [sp], #0x10
    0x186b700c0 <+32>: ret    
`

### Additional Information

* React Native version: react-native 0.49.5
* Development Operating System: macos
* Dev tools: xcode9, ios11

**Comment by AnnyA95** [comment]
Same issue with IphoneX

**Comment by AnnyA95** [comment]
Chenminhua
This can be fixed by adding the key: <key>NSPhotoLibraryAddUsageDescription</key> to your info.plist

**Comment by haitaoli** [comment]
Thanks @AnnyA95 for providing the solution.

**Comment by LingboTang** [comment]
@AnnyA95 I'm still having this issue after I add `NSPhotoLibraryAddUsageDescription` in info.plist

**Comment by AnnyA95** [comment]
@LingboTang which Iphone are you testing on?

**Comment by LingboTang** [comment]
@AnnyA95 Don't worry about it, I've already got it installed correctly, I think it is an Xcode caching issue. When I restarted Xcode, cleaned the old build and then built it again, the problem disappeared.

**Comment by FrozenPyrozen** [comment]
after I added another `NSPhotoLibraryUsageDescription` key info.plist, it all worked.

Example of my added code:
`
<key>NSPhotoLibraryAddUsageDescription</key>
<string>DESCRIPTION</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>DESCRIPTION</string>`
