### ISSUE TITLE
Prevent saving when choosing pic from gallery

### ISSUE THREAD

**Issue by emretekince** [react-community/react-native-image-picker#748]
When I choose an picture from gallery, it saves a copy of it again to gallery. How to prevent this?

**Comment by sami718** [comment]
var options = {
      storageOptions: {
        skipBackup: true,
        path: 'images'
      }
    };

**Comment by vemulanishanth** [comment]
skipBackup: true is for preventing iOS iCloud storage. Any more solutions please.
