### ISSUE TITLE
App Storage increasing with every image/video selected

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-community/react-native-image-picker#816]
### Description

Trying this library on IOS in a development environment - to a real device (iPad). Though it works nicely, I've noticed that it inflates the app storage quite significantly on picking an image or video, even though I'm not persisting the selected media in local or async storage, even if I don't try to render the chosen image in a component. But looking at Settings > General > iPad Storage > {my app} > Documents & Data the size increases by a few MB every time an image is picked (which is even more than the size of the file picked), even if I pick an existing image from the camera roll. Is this indicative of how the storage footprint will increase in a production app? I'd expect it to increase the memory footprint temporarily, but not to have a permanent impact on the app storage size.

### How to repeat issue and example

Use the library as per the example in the readme. Look at looking at Settings > General > iPad Storage > {app} > Documents & Data before & after an image or video is picked. Close & re-open the app & notice how this inflated size persists.

### Solution

Unknown

### Additional Information

* React Native version: 0.54.2
* Platform: iOS 11
* Development Operating System: MacOS

**Comment by slickdev** [comment]
I don't know if it's necessarily a bug. I use React Native FS (https://github.com/itinance/react-native-fs) to remove the temporary files and documents folder after I'm done processing the videos, and this allows me to keep the app storage sizes down.

**Comment by JeremyBradshaw7** [comment]
Thanks. Perhaps not a bug but definitely an issue I hit - though I'd expect the library to clean up after itself if it uses temporary storage, at least to ensure it is temporary! I'll try that library. Any code you could share on how you do that?
