### ISSUE TITLE
[Android] Permissions were not granted

### ISSUE THREAD

**Issue by beshur** [react-community/react-native-image-picker#845]
### Description

On my Nexus 5x (Android 6) emulator I click Allow for permissions request, but console always says **'ImagePicker Error: ', 'Permissions weren\'t granted'**
build.gradle has targetSdkVersion 22, compileSdkVersion 23.

### How to repeat issue and example

Trying to launch the image picker from example - clicking Take Photo or Select From Gallery.

### Solution

Should work.

### Additional Information

* React Native version: 0.55.2
* Platform: Android
* Development Operating System: OS X
* Dev tools: Android Studio 2.3.3, Android SDK up to 27

Thanks!

**Comment by beshur** [comment]
Also tried to lower the API version and build the app for my physical device with Android 5.0.1.

But it just crashes when triggering Take a Photo/Choose from library.
```
05-08 23:06:31.228 25746-25790/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.xpyry, PID: 25746
                                                   java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
                                                       at com.facebook.react.ReactActivityDelegate.requestPermissions
```

**Comment by nwaughachukwuma** [comment]
Hi @beshur am still having this issue, it says 

> Permissions weren\'t granted

**Comment by foo4foo** [comment]
Same problem on React-Native >= 0.55.

**Comment by jako-hub** [comment]
His solution works for me, but i'm very newe in React Native, in another project I had to add a provider in my AndroidManifest.xml and then, only then it works for me, maybe can help you.
```
      <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
      </provider>
``` 
And create this filepaths.xml

``` 
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="files"  path="/" />
</paths>
```

**Comment by korzonkiee** [comment]
I had to add `tools:node="replace"` to `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`:

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

because one of my packages already asked for `WRITE_EXTERNAL_STORAGE` permission with attribute `maxAndroidSdk=18`, so I had to override it.

**Comment by Anujmoglix** [comment]
The prefix "tools" for attribute "tools:node" associated with an element type "uses-permission" is not bound.

**Comment by rishiankush** [comment]
@Anujmoglix I am getting the same issue. How did you fix this?

**Comment by blake-spire** [comment]
> The prefix "tools" for attribute "tools:node" associated with an element type "uses-permission" is not bound.

you have to bind the tools attribute to your manifest element: 
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="[YOUR APP NAME]"
    xmlns:tools="http://schemas.android.com/tools"
    >`
