### ISSUE TITLE
Cannot read property 'showImagePicker' of undefined

### ISSUE THREAD

**Issue by juan-coding** [react-community/react-native-image-picker#861]
--- Delete everything above this line ---

### Description

I have installed react-native-image-picker for both Android and iOS. It works on Android simulator, but not on iOS. I have tried every possible solutions posted online, but nothing good happens.

<img width="278" alt="screen shot 2018-05-30 at 14 38 16" src="https://user-images.githubusercontent.com/15714764/40768348-5cbdff46-64b5-11e8-8919-9982a25cb2e6.png">

<img width="300" alt="screen shot 2018-05-30 at 14 36 12" src="https://user-images.githubusercontent.com/15714764/40768343-577c5730-64b5-11e8-807d-553bc332779e.png">
<img width="271" alt="screen shot 2018-05-30 at 14 41 53" src="https://user-images.githubusercontent.com/15714764/40768372-6d82435a-64b5-11e8-870c-e552b38d6f8e.png">
<img width="746" alt="screen shot 2018-05-30 at 14 42 09" src="https://user-images.githubusercontent.com/15714764/40768373-6d9d6c2a-64b5-11e8-9627-b8825ee90471.png">

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: "~0.55.2",
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode or Android Studio version, iOS or Android SDK version

**Comment by ilysorc** [comment]
is there any solution for this problem?

**Comment by ilysorc** [comment]
@juan-coding https://github.com/react-community/react-native-image-picker/issues/837 this solution works for me.

**Comment by juan-coding** [comment]
@ilysorc  After many hours of failures, I finally realised it can run normally on iOS real device via connecting my iPhone to Xcode, although it still doesn't work on the iOS simulator.

**Comment by juan-coding** [comment]
But still many Thanks for your attention.

**Comment by Baskerville42** [comment]
Have the same issue with Android
Solved by re-sync Gradle after linking

**Comment by wzup** [comment]
Manual linking solved the issue.
https://github.com/react-community/react-native-image-picker/issues/837#issuecomment-388014561

Too bad author can't write normal documentation

**Comment by LuisClark** [comment]
i have the same problem... i cant try run normally on iOS real device, because i'm no have devolper account yet, but doesn't work on the iOS simulator.

**Comment by LuisClark** [comment]
Fix this, getting in other Topic: 
**1. Add RNImagePicker from node_modules to Xcode
2. Then drag libRNImagePicker.a to Build Phases -> Link Binary with Libraries
3. After doing this go to build settings-> Header Search path and add the following line so that it will look for this library
$(SRCROOT)/../node_modules/react-native-image-picker/ios
4. Clean your project
5. Build your project and Run
It will run successfully.
Check enclosed image**

fix by @kaushal9678
https://github.com/react-native-community/react-native-image-picker/issues/957
