### ISSUE TITLE
[IOS] GPS Tags not available with react-native-image-picker openCamera

### ISSUE THREAD

**Issue by elribonazo** [react-community/react-native-image-picker#862]
### Description

First of all thanks for paying attention to this, lets hope we can find a solution together, I will be super happy to help and get this done.

When we use the module to load an image from the external source, the GPS location tags are correctly returned by the application.
Our bad happens when we call ImagePicker.launchCamera method with :

`
const options = {
            quality: 0.75,
            noData: true,
            maxWidth: 500,
            maxHeight: 500,
            storageOptions: {
                skipBackup: true
            }
        };
`

The user at this point has authorized the camera to register location tags (When taking a picture with the camera app, the location gets stored correctly) and he opens the camera + takes a picture.
The response callback of ImagePicker.launchCamera returns the image correctly, but without tags even if they are enabled in the camera app.

We've tried to use storageOptions properties to check if we could handle that but it is not working either after changing the properties so I see this as a bug.

### How to repeat issue and example
`const options = {
            quality: 0.75,
            noData: true,
            maxWidth: 500,
            maxHeight: 500,
            storageOptions: {
                skipBackup: true
            }
        };
        ImagePicker.launchCamera(options, async (response) => {
            if (!response.didCancel && !response.error) {
                //response does not have location tags
            }
        });`

Apart from that, even when storing in the camera roll, the picture does not contain GPS tags so its pretty clear that the GPS tags are not saved, or they are getting stripped.

I've also read in other issues that during the quality conversion or cropping the GPS tags get stripped but even if I remove this parameters the behavior remains.

## Investigations

ImagePickerManager.m, we find this peace of code:
`
if (imageURL) {
                PHAsset *pickedAsset = [PHAsset fetchAssetsWithALAssetURLs:@[imageURL] options:nil].lastObject;
                NSString *originalFilename = [self originalFilenameForAsset:pickedAsset assetType:PHAssetResourceTypePhoto];
                self.response[@"fileName"] = originalFilename ?: [NSNull null];
                if (pickedAsset.location) {
                    self.response[@"latitude"] = @(pickedAsset.location.coordinate.latitude);
                    self.response[@"longitude"] = @(pickedAsset.location.coordinate.longitude);
                }
                if (pickedAsset.creationDate) {
                    self.response[@"timestamp"] = [[ImagePickerManager ISO8601DateFormatter] stringFromDate:pickedAsset.creationDate];
                }
            }
`

ImageURL is null, hmmm its weird. I don't know a lot of objective-c but with a bit of explanation I think i will be able to implement a fix.

### Solution

That whenever the user takes a picture it respects the camera settings regarding the GPS location tags and that these tags are returned in the callback.

### Additional Information
* React Native image picker version: 0.26.7
* React Native version: 0.55.3
* Platform: Only on IOS
* Development Operating System:OSX
* Dev tools: Xcode debugging native code + RN debugger + chrome

**Comment by elribonazo** [comment]
Nooo... and we wont have any good news I think for a while.

The problem is because IOS doesn't write the GPS tags when you launch the camera to take a picture and the current native code in objective-c or swift doesn't let us pass settings or similar.

Sorry for that... 
What we finally did, is informing the user with a popup to take a picture from the camera directly and come back to the application later. At that point we check if the GPS tags of the last picture in the camera roll are available.

Hope that helps.

Br

**Comment by haifahrul** [comment]
> Nooo... and we wont have any good news I think for a while.
> 
> The problem is because IOS doesn't write the GPS tags when you launch the camera to take a picture and the current native code in objective-c or swift doesn't let us pass settings or similar.
> 
> Sorry for that...
> What we finally did, is informing the user with a popup to take a picture from the camera directly and come back to the application later. At that point we check if the GPS tags of the last picture in the camera roll are available.
> 
> Hope that helps.
> 
> Br

And How about Android?

**Comment by elribonazo** [comment]
Android, you open the camera, take a picture and once you are bsck to your app with the file and the metadata.

**Comment by haifahrul** [comment]
Can you check my issue @1043?

**Comment by pankti1210** [comment]
@haifahrul  have you found any solution yet ?
i am having the same issue.. can not get location info in response..

**Comment by elribonazo** [comment]
solution no... at least not backwards compatible with ios. As i said we ended up making that alert / popup to user, its not perfect but the ux is not that bad

**Comment by Ronielli** [comment]
Hi!
Solution????

**Comment by alexg-93** [comment]
any solution?
