### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GregTheGreek** [react-community/react-native-image-picker#865]
### Description

The app crashes when I take a photo and try to upload it to my server but when I choose from camera roll it does not fail and uploads successfully. The logic is identical for both methods.

### Code for saving to state.
```
 selectPhotoTapped() {
    const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true
      }
    };
    ImagePicker.showImagePicker(options, (response) => {
      if (response.didCancel) {
        console.log('User cancelled photo picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        this.setState({ image: response });
      }
    });
  }
```
### Additional Information

* React Native version: "^0.54.0
* Platform: iOS
* Development Operating System: OSX

**Comment by Torippana** [comment]
I have same issue
```
  "dependencies": {
    "firebase": "^4.6.2",
    "moment": "^2.22.2",
    "react": "16.2.0",
    "react-native": "0.53",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-image-picker": "^0.26.7",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-picker-select": "^3.1.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.8"
  },
```

**Comment by GregTheGreek** [comment]
So I found out my issue. Filename doesn't exist when you take a photo therefore my code was crashing when trying to .split() on the file name . Will make a pr for readme clarity

**Comment by Torippana** [comment]
thank you for giving me answer quickly.
How did you solve this problem? did you set some name when you take a photo??
sorry I'm kind of beginner of react native and ios app
please give some more information.

**Comment by Torippana** [comment]
> Avoid using filename.
I see, need to some setting about Avoid using filename for react-native-image-picker
Did you change source code on react-native-image picker? or some upload image file you made?

thanks Greg, It was big help for me realy

**Comment by Torippana** [comment]
@GregTheGreek could you tell me How do you Avoid using filename, Please??
I have been trying to solve this problem.

**Comment by GregTheGreek** [comment]
I just uri

On Jun 9, 2018 04:52, "Torippana" <notifications@github.com> wrote:

@GregTheGreek <https://github.com/GregTheGreek> could you tell me How do
you Avoid using filename, Please??
I have been trying to solve this problem.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/react-community/react-native-image-picker/issues/865#issuecomment-395952418>,
or mute the thread
