### ISSUE TITLE
Heic format

### ISSUE THREAD

**Issue by dlochynski** [react-community/react-native-image-picker#872]
Is there any way to deal with .heic images selection on the iPhones? I can't currently even pick them.

**Comment by b-d055** [comment]
Hi @dlochynski I got around this problem by noticing that all images have an uri (response.uri) that ends with .jpg. Even those images with a .heic file format and fileName. I simply use this .jpg uri when I want to do something with the image, including uploading to an API endpoint.

**Comment by dlochynski** [comment]
I must've ommited that. It was quite confusing for me that the format was different than the response.uri. Thanks a lot.

**Comment by AlMel3000** [comment]
Hi!
Somewhy iOS converts HEIC to jpg and MOV to mp4
So as I need uncompressed and uncchanged file I did so:

`    _selectImage() {

        const options = {
            noData: true,
            quality: 1,
            mediaType: 'mixed',
            videoQuality: 'high',
            permissionDenied: {
                title: LocalisationHandler.getAppLocale().permission_denied_title,
                text: LocalisationHandler.getAppLocale().permission_denied_message

            }
        };

        ImagePicker.launchImageLibrary(options, (response) => {
            console.warn('ImagePicker RESPONSE = ', response);

            if (response.didCancel) {
                console.warn('ImagePicker User cancelled image picker');
            }
            else if (response.error) {
                console.warn('ImagePicker Error: ', response.error);
            }
            else if (response.customButton) {
                console.warn('ImagePicker User tapped custom button: ', response.customButton);
            }
            else {
                let path;
                let uri = response.uri;
                let origURL;
                let imageName = response.fileName;
                if (Platform.OS === 'ios') {
                    path = null;
                    origURL = response.origURL;
                    isIosImage = true;
                } else {
                    path = response.path;
                }
                this.processFile(path, uri, imageName, origURL)
            }
        });

    }

    processFile(path, uri, fileName, origURL) {
        if (path !== null) {
            RNFS.hash(path, 'sha512')
                .then((result) => {
                    this.doSomeWork(result, fileName);
                });
        } else {
            RNFS.copyFile(uri, `${RNFS.TemporaryDirectoryPath}${fileName}`);
            RNFS.copyFile(origURL, `${RNFS.TemporaryDirectoryPath}${fileName}`);
            path = `${RNFS.TemporaryDirectoryPath}${fileName}`;
            console.warn('path : ', path);

            RNFS.hash(path, 'sha512')
                .then((result) => {
                    this.doSomeWork(result, fileName);
                        this.deleteTemporaryFile(path)
                    
                });
        }
    }`

It's not a perfect solution but it works for me

**Comment by afilp** [comment]
There is no `origURL` anymore in order to do our own conversion, correct?
