### ISSUE TITLE
Use fileStorage.path for Android

### ISSUE THREAD

**Issue by nathan-K-** [react-community/react-native-image-picker#885]
### Description

I want to be able to specify the option "fileStorage.path" on Android, so the picture will be saved under picture/[path]/x.jpg

### How to repeat issue and example

Your explanation here and source code or link

### Solution

Minor change in MediaUtils.java can do the trick, see the PR #886 .

### Additional Information

* React Native version: 0.55.3
* Platform: Android, emulator with SDK 23 and smartphone with Android 6.0
* Development Operating System: Linux
* Dev tools: WebStorm

**Comment by charpeni** [comment]
Added with 7b9ff643c7c7353eda4a9e010efc62ad7a355314.
