### ISSUE TITLE
showImagePicker method in android crash  at  this.setState({  avatarSource: source }); for compile sdk: 8.0 and build tool version: 26.0.1 .Getting below output

### ISSUE THREAD

**Issue by penmatsa** [react-community/react-native-image-picker#889]
![screenshot_20180710-171954_afterschool](https://user-images.githubusercontent.com/5647811/42514435-0cd578f6-8477-11e8-9030-b80554de4978.jpg)

**Comment by MiguelMelo** [comment]
I have the same problem...

**Comment by penmatsa** [comment]
above works when showImagePicker method  is called inside a method "Which should be bind in constructor"
