### ISSUE TITLE
Camera wont open but camera roll works fine (out of nowhere) IOS **RESOLVED**

### ISSUE THREAD

**Issue by nica0012** [react-community/react-native-image-picker#930]
Hi everyone, 

I've been using the imager picker and everything has been working great. this past week I have not been able to open the camera. When I press take photo nothing happens (no errors either).
I have everything set up in xcode - I tried over and over to remove the library and add it / link / re-add the info.plist lines but still haven't been able to resolve this.

RN version: 0.55.4
react-native-image-picker version: 0.26.10

I appreciate all the help I can get! 
Cheers.

**Comment by JB-CHAUVIN** [comment]
Hello, same issue goes for me...

**Comment by nica0012** [comment]
@JB-CHAUVIN I will let you know if I resolve this, please do the same!

**Comment by alsotang** [comment]
same issue for me. no any error message.

**Comment by alsotang** [comment]
https://github.com/react-community/react-native-image-picker/blob/abcd82982889cc28aaf3b8b680c547cbd6da19dd/ios/ImagePickerManager.m#L138
![image](https://user-images.githubusercontent.com/1147375/46255971-cc093100-c4d6-11e8-89e9-ba23eba784d8.png)

**Comment by alsotang** [comment]
dont use simulator. use a true iphone.

**Comment by nica0012** [comment]
@alsotang I have tried my iPhone. I had no issues until all of a sudden it stopped working - no errors on the phone too.

**Comment by sinclas** [comment]
Did this get resolved? I am having the same issue on Android.  The photos lib works, but the camera does not. It used to work last week.   I have to go look at my change logs... unless someone has a quick response!  thanks!

**Comment by nica0012** [comment]
@sinclas Still no luck... I've been getting pretty frustrated with the issue and am not looking forward to potentially switching it up... There seems to be no support anymore.

**Comment by nica0012** [comment]
After updating to version 27 + everything is working.
