### ISSUE TITLE
Deploy a new version: 0.2x.x

### ISSUE THREAD

**Issue by jmcartlamy** [react-community/react-native-image-picker#943]
### Description

A [critical commit](https://github.com/react-community/react-native-image-picker/commit/8187eaf1ca308c0737ed13e96f98bd0033ca160e 
) has been merged to the branche #master. This commit fix an issue about the release build for Android. 

Actually, an error failed the release build for Android.

### How to repeat issue and example

Just try to use react-native-image-picker@0.26.10 with React Native +0.56.0

### Solution

Could you bump `react-native-image-picker` to a new stable version ? (after some tests of course)

Thank you.

**Comment by charpeni** [comment]
Thanks for the heads up! 

I'm currently working on a new release, I'm going through all pull requests, doing some refactoring, and hopefully, I will be able to release a stable version at the end of the week!

In the meantime, you can review any PRs that you need and ping me.

I'll close this issue, but if you have any question, feel free to ping me here.

**Comment by charpeni** [comment]
`0.27.0` is out!
