### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by GuillaumeAmat** [react-community/react-native-image-picker#946]
Hi there 👋

Is it planned to release a new version soon. The current one is too old so we have too directly use master, which is unfortunate...

**Comment by GuillaumeAmat** [comment]
Ah, I did not see that issue: #943 

My bad!

**Comment by charpeni** [comment]
No worries, `0.27.0` is out now. 😄

**Comment by GuillaumeAmat** [comment]
Freat thanks :)
