### ISSUE TITLE
png image has a white background instead of being transparent

### ISSUE THREAD

**Issue by nica0012** [react-community/react-native-image-picker#965]
## Description

When picking a png image which is to be used as a logo, the transparent background of the logo is solid white, when editing is enabled the background is then black. 

I have seen another similar issue but no answer.

### Additional Information

RN Version: 0.57.4
React Native Image Picker Version: 0.27.1

Thank you.

**Comment by nica0012** [comment]
Turns out using origUri instead of uri fixes the issue.

**Comment by Urvish123** [comment]
write in image style={{  position:'absolute'}}
