### ISSUE TITLE
why take photo can't upload the photo file

### ISSUE THREAD

**Issue by mqy1023** [react-community/react-native-image-picker#969]
choose picture from mobile can show avatarSource, but take photo can't use below code to show photo
```
const source = {uri: response.uri};
this.setState({ avatarSource: source});
```
and upload img file from take photo don't work
```
 formdata.append('file', {uri: response.uri, type: 'application/octet-stream', name: response.fileName});
```

**Comment by socheat1994** [comment]
@mqy1023  solved it yet?. and how ?

**Comment by HarshitMadhav** [comment]
Any solution to this?

**Comment by Kimsohyuncans** [comment]
> I think the problem is about fileName property. In case of taking photo, fileName will be **null**. Null file name causes uploading issue on the server. Just a simple check may solve your issue too. @HarshitMadhav @socheat1994
> 
> E.g.:
> 
> ```js
> let formData = new FormData();
> formData.append('file', {
>     uri: response.uri,
>     type: 'image/jpeg',
>     name: response.fileName ? response.fileName : new Date().getTime()
> });
> ```

it's work for me

**Comment by yalcinozer** [comment]
> I think the problem is about fileName property. In case of taking photo, fileName will be **null**. Null file name causes uploading issue on the server. Just a simple check may solve your issue too. @HarshitMadhav @socheat1994
> 
> E.g.:
> 
> ```js
> let formData = new FormData();
> formData.append('file', {
>     uri: response.uri,
>     type: 'image/jpeg',
>     name: response.fileName ? response.fileName : new Date().getTime()
> });
> ```

Thanks. Actually image picker was giving me a name, but I wanted to try your solution, removed it and wrote a static string. BINGO. It works :-)

**Comment by aliemre** [comment]
It will work in your way, too. Picker does not provide file name in case of taking photo (I dont know why). If you pick a photo from gallery, the file name is provided. :)

**Comment by yalcinozer** [comment]
I can log the responde and it prints name something like that:
`rn_image_picker_lib_temp_4e44269d-6e60-4185-9ea0-a21fa3627093.jpg`
But using this value as name in append causes problem, I dont know the reason.
