### ISSUE TITLE
Launching Image Library causes app to crash

### ISSUE THREAD

**Issue by jvntf** [react-community/react-native-image-picker#976]
### Description

Using the provided example and my own version of the code, launching the ImageLibrary causes the IOS simulator to crash the app. The option menu to choose camera or library opens, but crashes after the user makes a choice. I have already added the keys to the Info.plist file to state camera / photos access.

### How to repeat issue and example

```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Alert, Button} from 'react-native';
import ImagePicker from 'react-native-image-picker'
import Permissions from 'react-native-permissions'

type Props = {};

export default class App extends Component {
  state = {
      modalVisible: false,
      photos: [],
      index: null
  }
  _onPressButton() {
    // Alert.alert("button")
      ImagePicker.showImagePicker( {},(response) => {
        console.log('Response = ', response);

          if (response.didCancel) {
            console.log('User cancelled image picker');
          } else if (response.error) {
            console.log('ImagePicker Error: ', response.error);
          } else if (response.customButton) {
            console.log('User tapped custom button: ', response.customButton);
          } else {
            const source = { uri: response.uri };

            // You can also display the image using data:
            // const source = { uri: 'data:image/jpeg;base64,' + response.data };

            this.setState({
              avatarSource: source,
            });
          }
      })

    
  }
  render() {
    return (
      <View style={styles.container}>
        <View style={[styles.btnContainer, styles.btnCamRoll]}>
          <Button
            style
            onPress={this._onPressButton}
            title="Open Camera Roll"
            />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  btnContainer:{
    margin:20
  },
  btnCamRoll:{
    position:'absolute',
    bottom:0
  }
});
```

### Additional Information

* React Native version: 0.57.4
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode 10.1, iOS 12.1

**Comment by Demeny** [comment]
I've solved this issue by adding the following to my `info.plist` 

`	<key>NSPhotoLibraryUsageDescription</key>
	<string>Images from Library</string>
	<key>NSCameraUsageDescription</key>
	<string>Images from Camera</string>`

**Comment by jvntf** [comment]
in `ios/build/info.plist` or `ios/<app-name>/Info.plist`?
Do I need to request permission from the user first?

**Comment by charpeni** [comment]
Refer to the post install steps on iOS: https://github.com/react-community/react-native-image-picker/blob/master/docs/Install.md#post-install-steps

**Comment by CyrusZei** [comment]
Make sure that you put the privacy rights in the correct Info.plist

you have on in the root folder(if you are using firebase)
and then you have one in <appname>/Info.plist
